### ISSUE TITLE
Home Page Visual Enhancements

### ISSUE THREAD

**Issue by diogohalmeida** [FEUP-ESOF-2020-21/open-cx-t1g1-ploggers#43]
Final interface for the Home Page
Development Report: [User Story 13](https://github.com/FEUP-ESOF-2020-21/open-cx-t1g1-ploggers#story-13)

**Comment by jcpinto54** [comment]
Reparei que quando se faz swipe a mudar de pagina no menu inicial, a barra de navegação não atualiza a página em que está. Não sabia se criava um novo issue acerca disto, mas pareceu-me que caia neste tópico

**Comment by diogohalmeida** [comment]
Sim isso é por causa de um problema no Page View na Navigation Bar, a solução ideal seria mesmo desativar o swipe e ficarmos só pela barra de navegação. Podemos incluir esse problema nesta secção
